/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 04-oct.-2021 7:35:46 p. m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `Actividades_Campania` CASCADE
;

DROP TABLE IF EXISTS `Barrios` CASCADE
;

DROP TABLE IF EXISTS `Campanias` CASCADE
;

DROP TABLE IF EXISTS `Candidatos` CASCADE
;

DROP TABLE IF EXISTS `ciudades` CASCADE
;

DROP TABLE IF EXISTS `Ciudades_Zonas` CASCADE
;

DROP TABLE IF EXISTS `Compromisos` CASCADE
;

DROP TABLE IF EXISTS `Comunas` CASCADE
;

DROP TABLE IF EXISTS `Coordinadores` CASCADE
;

DROP TABLE IF EXISTS `Coordinadores_Lideres` CASCADE
;

DROP TABLE IF EXISTS `Corregimientos` CASCADE
;

DROP TABLE IF EXISTS `Departamentos` CASCADE
;

DROP TABLE IF EXISTS `Directorios_Campanias` CASCADE
;

DROP TABLE IF EXISTS `Lideres` CASCADE
;

DROP TABLE IF EXISTS `Lideres_Personas` CASCADE
;

DROP TABLE IF EXISTS `Mesas_Votacion` CASCADE
;

DROP TABLE IF EXISTS `Perfiles` CASCADE
;

DROP TABLE IF EXISTS `Perfiles_Roles` CASCADE
;

DROP TABLE IF EXISTS `Personas` CASCADE
;

DROP TABLE IF EXISTS `Publicidad` CASCADE
;

DROP TABLE IF EXISTS `Puestos_Votacion` CASCADE
;

DROP TABLE IF EXISTS `Roles` CASCADE
;

DROP TABLE IF EXISTS `Usuarios` CASCADE
;

DROP TABLE IF EXISTS `Valores_Dominio` CASCADE
;

DROP TABLE IF EXISTS `Veredas` CASCADE
;

DROP TABLE IF EXISTS `Zonas` CASCADE
;

/* Create Tables */

CREATE TABLE `Actividades_Campania`
(
	`id_actividad` DECIMAL(10,2) NOT NULL,
	`fec_actividad` TIMESTAMP(4) NULL,
	`id_campania` DECIMAL(10,2) NULL,
	`nom_actividad` VARCHAR(250) NULL,
	`direccion` VARCHAR(250) NULL,
	`hora_actividad` DECIMAL(10,2) NULL,
	CONSTRAINT `PK_Actividades_Campania` PRIMARY KEY (`id_actividad` ASC)
)

;

CREATE TABLE `Barrios`
(
	`id_barrio` DECIMAL(10,2) NOT NULL,
	`id_comuna` DECIMAL(10,2) NULL,
	`nom_barrio` VARCHAR(250) NULL,
	`fec_cambio` TIMESTAMP NULL,
	CONSTRAINT `PK_Barrios` PRIMARY KEY (`id_barrio` ASC)
)

;

CREATE TABLE `Campanias`
(
	`id_campania` DECIMAL(10,2) NOT NULL,
	`tipo_campania` DECIMAL(10,2) NULL,
	`nom_campania` VARCHAR(250) NULL,
	`logo_campania` BLOB NULL,
	`id_candidato` DECIMAL(10,2) NULL,
	CONSTRAINT `PK_Campanias` PRIMARY KEY (`id_campania` ASC)
)

;

CREATE TABLE `Candidatos`
(
	`id_candidato` DECIMAL(10,2) NOT NULL,
	`nom_candidato` VARCHAR(250) NULL,
	`fec_cambio` TIMESTAMP NULL,
	`foto` BLOB NULL,
	`descripcion` VARCHAR(500) NULL,
	CONSTRAINT `PK_Candidatos` PRIMARY KEY (`id_candidato` ASC)
)

;

CREATE TABLE `ciudades`
(
	`id_ciudad` DECIMAL(10,2) NOT NULL,
	`id_departamento` DECIMAL(10,2) NOT NULL,
	`nom_departamento` VARCHAR(250) NULL,
	`fec_cambio` TIMESTAMP NULL,
	CONSTRAINT `PK_Ciudades` PRIMARY KEY (`id_ciudad` ASC, `id_departamento` ASC)
)

;

CREATE TABLE `Ciudades_Zonas`
(
	`id_ciudad_zona` DECIMAL(10,2) NOT NULL,
	`id_ciudad` DECIMAL(10,2) NULL,
	`id_departamento` VARCHAR(50) NULL,
	`id_zona` DECIMAL(10,2) NULL,
	CONSTRAINT `PK_Ciudades_Zonas` PRIMARY KEY (`id_ciudad_zona` ASC)
)

;

CREATE TABLE `Compromisos`
(
	`id_compromiso` DECIMAL(10,2) NOT NULL,
	`fec_inicial` DATE NULL,
	`id_campania` DECIMAL(10,2) NULL,
	`fec_final` DATE NULL,
	`id_lider` DECIMAL(10,2) NULL,
	`tipo_compromiso` DECIMAL(10,2) NULL,
	`id_persona` DECIMAL(10,2) NULL,
	`nom_compromiso` VARCHAR(250) NULL,
	CONSTRAINT `PK_Compromisos` PRIMARY KEY (`id_compromiso` ASC)
)

;

CREATE TABLE `Comunas`
(
	`id_comuna` DECIMAL(10,2) NOT NULL,
	`id_ciudad` DECIMAL(10,2) NULL,
	`id_departamento` DECIMAL(10,2) NULL,
	`nom_comuna` VARCHAR(250) NULL,
	`fec_cambio` TIMESTAMP NULL,
	CONSTRAINT `PK_Comunas` PRIMARY KEY (`id_comuna` ASC)
)

;

CREATE TABLE `Coordinadores`
(
	`id_coordinador` DECIMAL(10,2) NOT NULL,
	`id_zona` DECIMAL(10,2) NULL,
	`nom_coordinador` VARCHAR(250) NULL,
	`fec_cambio` TIMESTAMP NULL,
	CONSTRAINT `PK_Coordinadores` PRIMARY KEY (`id_coordinador` ASC)
)

;

CREATE TABLE `Coordinadores_Lideres`
(
	`id_coordlider` DECIMAL(10,2) NOT NULL,
	`id_lider` DECIMAL(10,2) NULL,
	`id_campania` DECIMAL(10,2) NULL,
	`id_coordinador` DECIMAL(10,2) NULL,
	CONSTRAINT `PK_Cordinadores_Lideres` PRIMARY KEY (`id_coordlider` ASC)
)

;

CREATE TABLE `Corregimientos`
(
	`id_corregimiento` DECIMAL(10,2) NOT NULL,
	`id_ciudad` DECIMAL(10,2) NULL,
	`id_departamento` DECIMAL(10,2) NULL,
	`nom_corregimiento` VARCHAR(250) NULL,
	`fec_cambio` TIMESTAMP NULL,
	CONSTRAINT `PK_Corregimientos` PRIMARY KEY (`id_corregimiento` ASC)
)

;

CREATE TABLE `Departamentos`
(
	`id_departamento` DECIMAL(10,2) NOT NULL,
	`nom_departamento` VARCHAR(250) NULL,
	`fec_cambio` TIMESTAMP NULL,
	CONSTRAINT `PK_Departamentos` PRIMARY KEY (`id_departamento` ASC)
)

;

CREATE TABLE `Directorios_Campanias`
(
	`id_directorio` DECIMAL(10,2) NOT NULL,
	`id_zona` DECIMAL(10,2) NULL,
	`id_campania` DECIMAL(10,2) NULL,
	`id_ciudad` DECIMAL(10,2) NULL,
	`id_departamento` VARCHAR(50) NULL,
	`nom_directorio` VARCHAR(250) NULL,
	CONSTRAINT `PK_Directorios_Campania` PRIMARY KEY (`id_directorio` ASC)
)

;

CREATE TABLE `Lideres`
(
	`id_lider` DECIMAL(10,2) NOT NULL,
	`id_campania` DECIMAL(10,2) NOT NULL,
	`id_usuario` DECIMAL(10,2) NULL,
	`tipo_lider` DECIMAL(10,2) NULL,
	`id_ciudad` DECIMAL(10,2) NULL,
	`id_departamento` DECIMAL(10,2) NULL,
	`nom_lider` VARCHAR(250) NULL,
	CONSTRAINT `PK_Lideres` PRIMARY KEY (`id_lider` ASC, `id_campania` ASC)
)

;

CREATE TABLE `Lideres_Personas`
(
	`id_lider_persona` DECIMAL(10,2) NULL,
	`id_lider` DECIMAL(10,2) NULL,
	`id_persona` DECIMAL(10,2) NULL,
	`id_campania` DECIMAL(10,2) NULL
)

;

CREATE TABLE `Mesas_Votacion`
(
	`id_mesa` DECIMAL(10,2) NOT NULL,
	`nom_mesa` VARCHAR(50) NULL,
	`id_puesto` DECIMAL(10,2) NULL,
	CONSTRAINT `PK_Mesas_Votacion` PRIMARY KEY (`id_mesa` ASC)
)

;

CREATE TABLE `Perfiles`
(
	`id_perfil` DECIMAL(10,2) NOT NULL,
	`nom_perfil` VARCHAR(250) NULL,
	`descripcion` VARCHAR(500) NULL,
	`fec_cambio` TIMESTAMP NULL,
	CONSTRAINT `PK_Perfiles` PRIMARY KEY (`id_perfil` ASC)
)

;

CREATE TABLE `Perfiles_Roles`
(
	`id_perfil_rol` DECIMAL(10,2) NOT NULL,
	`id_rol` DECIMAL(10,2) NULL,
	`fec_cambio` TIMESTAMP NULL,
	`id_perfil` DECIMAL(10,2) NULL,
	CONSTRAINT `PK_perfiles_roles` PRIMARY KEY (`id_perfil_rol` ASC)
)

;

CREATE TABLE `Personas`
(
	`id_persona` DECIMAL(10,2) NOT NULL,
	`pri_nombre` VARCHAR(250) NULL,
	`seg_nombre` VARCHAR(250) NULL,
	`pri_apellido` VARCHAR(250) NULL,
	`seg_apellido` VARCHAR(250) NULL,
	`tipo_identificacion` DECIMAL(10,2) NULL,
	`num_identificacion` VARCHAR(250) NULL,
	`email` VARCHAR(250) NULL,
	`direccion` VARCHAR(250) NULL,
	`telefono` DECIMAL(10,2) NULL,
	`razon_social` VARCHAR(500) NULL,
	`genero` DECIMAL(10,2) NULL,
	`id_zona` DECIMAL(10,2) NULL,
	`id_mesa` DECIMAL(10,2) NULL,
	CONSTRAINT `PK_Personas` PRIMARY KEY (`id_persona` ASC)
)

;

CREATE TABLE `Publicidad`
(
	`id_publicidad` DECIMAL(10,2) NOT NULL,
	`id_campania` DECIMAL(10,2) NULL,
	`nom_publicidad` VARCHAR(250) NULL,
	CONSTRAINT `PK_Publicidad` PRIMARY KEY (`id_publicidad` ASC)
)

;

CREATE TABLE `Puestos_Votacion`
(
	`id_puesto` DECIMAL(10,2) NOT NULL,
	`nom_puesto` VARCHAR(250) NULL,
	`direccion` VARCHAR(500) NULL,
	CONSTRAINT `PK_Puestos_Votacion` PRIMARY KEY (`id_puesto` ASC)
)

;

CREATE TABLE `Roles`
(
	`id_rol` DECIMAL(10,2) NOT NULL,
	`nom_rol` VARCHAR(250) NULL,
	`descripcion` VARCHAR(500) NULL,
	`fec_cambio` TIMESTAMP NULL,
	CONSTRAINT `PK_Roles` PRIMARY KEY (`id_rol` ASC)
)

;

CREATE TABLE `Usuarios`
(
	`id_usuario` DECIMAL(10,2) NOT NULL,
	`nom_usuario` VARCHAR(250) NULL,
	`fec_cambio` TIMESTAMP NULL,
	`id_perfil` DECIMAL(10,2) NULL,
	`password` VARCHAR(500) NULL,
	`id_persona` DECIMAL(10,2) NULL,
	CONSTRAINT `PK_Usuarios` PRIMARY KEY (`id_usuario` ASC)
)

;

CREATE TABLE `Valores_Dominio`
(
	`id_valor_dominio` DECIMAL(10,2) NOT NULL,
	`cod_dominio` DECIMAL(10,2) NULL,
	`val_dominio` VARCHAR(250) NULL,
	`fec_cambio` TIMESTAMP NULL,
	`nom_valor_dominio` VARCHAR(250) NULL,
	CONSTRAINT `PK_valores_dominio` PRIMARY KEY (`id_valor_dominio` ASC)
)

;

CREATE TABLE `Veredas`
(
	`id_vereda` DECIMAL(10,2) NOT NULL,
	`id_corregimiento` DECIMAL(10,2) NULL,
	`id_ciudad` DECIMAL(10,2) NULL,
	`id_departamento` DECIMAL(10,2) NULL,
	`nom_vereda` VARCHAR(250) NULL,
	`fec_cambio` TIMESTAMP NULL,
	CONSTRAINT `PK_Veredas` PRIMARY KEY (`id_vereda` ASC)
)

;

CREATE TABLE `Zonas`
(
	`id_zona` DECIMAL(10,2) NOT NULL,
	`nom_zona` VARCHAR(250) NULL,
	`fec_cambio` TIMESTAMP NULL,
	CONSTRAINT `PK_Zonas` PRIMARY KEY (`id_zona` ASC)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `Actividades_Campania` 
 ADD CONSTRAINT `FK_Actividades_Campania_Campanias`
	FOREIGN KEY (`id_campania`) REFERENCES `Campanias` (`id_campania`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Barrios` 
 ADD CONSTRAINT `FK_Barrios_Comunas`
	FOREIGN KEY (`id_comuna`) REFERENCES `Comunas` (`id_comuna`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Campanias` 
 ADD CONSTRAINT `FK_Campanias_Candidatos`
	FOREIGN KEY (`id_candidato`) REFERENCES `Candidatos` (`id_candidato`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `ciudades` 
 ADD CONSTRAINT `FK_ciudades_Departamentos`
	FOREIGN KEY (`id_departamento`) REFERENCES `Departamentos` (`id_departamento`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Ciudades_Zonas` 
 ADD CONSTRAINT `FK_Ciudades_Zonas_ciudades`
	FOREIGN KEY (`id_ciudad`, `id_departamento`) REFERENCES `ciudades` (`id_ciudad`,`id_departamento`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Ciudades_Zonas` 
 ADD CONSTRAINT `FK_Ciudades_Zonas_Zonas`
	FOREIGN KEY (`id_zona`) REFERENCES `Zonas` (`id_zona`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Compromisos` 
 ADD CONSTRAINT `FK_Compromisos_Campanias`
	FOREIGN KEY (`id_campania`) REFERENCES `Campanias` (`id_campania`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Compromisos` 
 ADD CONSTRAINT `FK_Compromisos_Lideres`
	FOREIGN KEY (`id_lider`, `id_campania`) REFERENCES `Lideres` (`id_lider`,`id_campania`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Compromisos` 
 ADD CONSTRAINT `FK_Compromisos_Personas`
	FOREIGN KEY (`id_persona`) REFERENCES `Personas` (`id_persona`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Comunas` 
 ADD CONSTRAINT `FK_Comunas_ciudades`
	FOREIGN KEY (`id_ciudad`, `id_departamento`) REFERENCES `ciudades` (`id_ciudad`,`id_departamento`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Coordinadores` 
 ADD CONSTRAINT `FK_Coordinadores_Zonas`
	FOREIGN KEY (`id_zona`) REFERENCES `Zonas` (`id_zona`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Coordinadores_Lideres` 
 ADD CONSTRAINT `FK_Cordinadores_Lideres_Coordinadores`
	FOREIGN KEY (`id_coordinador`) REFERENCES `Coordinadores` (`id_coordinador`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Coordinadores_Lideres` 
 ADD CONSTRAINT `FK_Cordinadores_Lideres_Lideres`
	FOREIGN KEY (`id_lider`, `id_campania`) REFERENCES `Lideres` (`id_lider`,`id_campania`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Corregimientos` 
 ADD CONSTRAINT `FK_Corregimientos_ciudades`
	FOREIGN KEY (`id_ciudad`, `id_departamento`) REFERENCES `ciudades` (`id_ciudad`,`id_departamento`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Directorios_Campanias` 
 ADD CONSTRAINT `FK_Directorios_Campanias_Campanias`
	FOREIGN KEY (`id_campania`) REFERENCES `Campanias` (`id_campania`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Directorios_Campanias` 
 ADD CONSTRAINT `FK_Directorios_Campanias_ciudades`
	FOREIGN KEY (`id_ciudad`, `id_departamento`) REFERENCES `ciudades` (`id_ciudad`,`id_departamento`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Lideres` 
 ADD CONSTRAINT `FK_Lideres_Campanias`
	FOREIGN KEY (`id_campania`) REFERENCES `Campanias` (`id_campania`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Lideres` 
 ADD CONSTRAINT `FK_Lideres_ciudades`
	FOREIGN KEY (`id_ciudad`, `id_departamento`) REFERENCES `ciudades` (`id_ciudad`,`id_departamento`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Lideres` 
 ADD CONSTRAINT `FK_Lideres_Usuarios`
	FOREIGN KEY (`id_usuario`) REFERENCES `Usuarios` (`id_usuario`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Lideres_Personas` 
 ADD CONSTRAINT `FK_Lideres_Personas_Personas`
	FOREIGN KEY (`id_persona`) REFERENCES `Personas` (`id_persona`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Mesas_Votacion` 
 ADD CONSTRAINT `FK_Mesas_Votacion_Puestos_Votacion`
	FOREIGN KEY (`id_puesto`) REFERENCES `Puestos_Votacion` (`id_puesto`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Perfiles_Roles` 
 ADD CONSTRAINT `FK_perfiles_roles_Perfiles`
	FOREIGN KEY (`id_perfil`) REFERENCES `Perfiles` (`id_perfil`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Perfiles_Roles` 
 ADD CONSTRAINT `FK_perfiles_roles_Roles`
	FOREIGN KEY (`id_rol`) REFERENCES `Roles` (`id_rol`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Personas` 
 ADD CONSTRAINT `FK_Personas_Mesas_Votacion`
	FOREIGN KEY (`id_mesa`) REFERENCES `Mesas_Votacion` (`id_mesa`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Personas` 
 ADD CONSTRAINT `FK_Personas_Zonas`
	FOREIGN KEY (`id_zona`) REFERENCES `Zonas` (`id_zona`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Publicidad` 
 ADD CONSTRAINT `FK_Publicidad_Campanias`
	FOREIGN KEY (`id_campania`) REFERENCES `Campanias` (`id_campania`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Usuarios` 
 ADD CONSTRAINT `FK_Usuarios_Perfiles`
	FOREIGN KEY (`id_perfil`) REFERENCES `Perfiles` (`id_perfil`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Usuarios` 
 ADD CONSTRAINT `FK_Usuarios_Personas`
	FOREIGN KEY (`id_persona`) REFERENCES `Personas` (`id_persona`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Veredas` 
 ADD CONSTRAINT `FK_Veredas_ciudades`
	FOREIGN KEY (`id_ciudad`, `id_departamento`) REFERENCES `ciudades` (`id_ciudad`,`id_departamento`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1 
;
